spring:
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: usuario-roteiro-conectado
          uri: lb://usuario-roteiro-conectado
          predicates:
            - Path=/usuario/**

        - id: usuario-roteiro-conectado
          uri: lb://usuario-roteiro-conectado
          predicates:
            - Path=/oauth2/**

        - id: roteiro-conectado
          uri: lb://roteiro-conectado
          predicates:
            - Path=/viagem/**

        - id: roteiro-conectado
          uri: lb://roteiro-conectado
          predicates:
            - Path=/hospedagem/**

        - id: roteiro-conectado
          uri: lb://roteiro-conectado
          predicates:
            - Path=/passagem/**

        - id: roteiro-conectado
          uri: lb://roteiro-conectado
          predicates:
            - Path=/roteiro/**



  application:
    name: api-gateway
server:
  port: 9091

eureka:
  instance:
    client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"